user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    server {
        listen 80;
        server_name localhost;

        # Serve static site from /usr/share/nginx/html
        root /usr/share/nginx/html;
        index index.html index.htm;



        # Standard location block for all other files
        location / {
            try_files $uri $uri/ =404;
        }

        # Serve JavaScript files with specific caching and MIME type handling
        location .js$ {
            root /usr/share/nginx/html;
            expires 7d;  # Cache JavaScript files for 7 days
            add_header Content-Type application/javascript;  # Explicit MIME type
            access_log off;  # Disable access logging for these requests
        }

        # Serve PNG files with specific caching and MIME type handling
        location ~* \.png$ {
            root /usr/share/nginx/html;
            expires 30d;  # Cache PNG images for 30 days
            add_header Content-Type image/png;  # Explicit MIME type
            access_log off;  # Disable access logging for these requests
        }

        # Error handling
        error_page 404 /404.html;
        location = /404.html {
            internal;
        }
    }
}

